version: '3.7'

services:

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    # command: gunicorn -b 0.0.0.0:5000 todosapp.wsgi:application
    # volumes:
    #   - .:/usr/src/app
    ports:
      - "5000:5000"
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true