version: '3.8'

services:

  backend:
    image: webapp-flask
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn -w 2 -b :5000 app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - ./.env.prod
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - 3000:3000
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    restart: on-failure