version: '3.8'

services:

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - ./.env.prod
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - 3000:80
    # environment:
    #   - CHOKIDAR_USEPOLLING=true